# Generated by Django 2.2.2 on 2019-06-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clone', '0002_repoclone_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repoclone',
            old_name='url',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='repoclone',
            old_name='directory',
            new_name='Directory',
        ),
        migrations.RenameField(
            model_name='repoclone',
            old_name='status',
            new_name='Status',
        ),
    ]
