# Generated by Django 2.2.2 on 2019-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='_location',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='_pre_requisite_courses_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='advertised_start',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='announcement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='catalog_visibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='cert_name_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='cert_name_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='certificates_display_behavior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='course_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='course_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='coursekey',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='days_early_for_beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='effort',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='end_of_course_survey_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='enrollment_domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='lowest_passing_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='marketing_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='max_student_enrollments_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='social_sharing_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
