# Generated by Django 2.2.1 on 2019-06-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_course', '0001_initial'),
        ('get_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedplatforms',
            name='courses',
            field=models.ManyToManyField(to='get_course.CourseOverview'),
        ),
    ]
