# Generated by Django 2.2.2 on 2019-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_platform', '0005_auto_20190621_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratedplatforms',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
